### PR TITLE
runtime: add kernel features auto-detection

### PR DESCRIPTION
**Pull request by lucab**
This introduces a module with some methods to detect kernel features
at runtime.

Fixes https://github.com/lucab/caps-rs/issues/7

### CODE REVIEW

**Comment by lucab** [comment]
@aep this should take care of your legacy kernels. You may want to run there the "legacy" example there and check that the detection logic is working properly.

**Comment by aep** [comment]
@bkchr

**Comment by bkchr** [comment]
I'm unsure, but I think your changes work. I get the following output on MIPS:
```
root@900:/tmp# ./legacy 
Ambient set supported: true
Unsupported new capabilities: []
```

**Comment by lucab** [comment]
@bkchr which kernel is that running on? If it is anything <4.3 then this PR is wrong.

Ideally, running on anything <3.16 should show some meaningful output.

**Comment by bkchr** [comment]
```Linux 4.4.92 #0 Tue Oct 17 17:46:20 2017 mips GNU/Linux```

So, I can't help you. Sorry. 
Maybe @aep can say where he uses such an old kernel.

**Comment by lucab** [comment]
I successfully tested the `legacy` example on Linux 3.2 kernel. Merging.

**Pull request merged**
