### PR TITLE
Replace `CapsError` with `std::io::Result`

### PR DESCRIPTION
**Pull request by npmccallum**
There are a few downsides to this patch:
1. It is a minor API break with the 0.5 release.
2. It discards a few custom error strings.

However, I believe the upsides outweight the downsides.

1. It removes seven of the eight crates in the dependency graph.
2. Wrapping C APIs with `std::io::Result` is extremely common and
   reduces the friction of using this library adjacent to other APIs
   that use `std::io::Result`.

### CODE REVIEW

**Comment by npmccallum** [comment]
FYI, I also plan to submit [this commit](https://github.com/npmccallum/caps-rs/commit/da5aaeb42ad1ea54a291a491330771d7ac2b5ccb) if this patch is accepted.

**Comment by lucab** [comment]
Thanks for the PR! No problem in taking an API break for this.

However I don't think this a nice way to go, as it discard a lot of useful context around low-level failures, which will in turn make debugging at runtime more painful. I'm not talking hypothetical, I already went through the pains of missing contexts in some obscure corner-cases here.

Taking a step back, are your maybe feeling that `thiserror` is bringing in too much dependency/building weight? If so, perhaps we can drop the derive approach and implement the same logic manually?

Or is your other patch having impedance mismatches around error types? In that case I think it may be enough to bridge the error type from<->into io::Error, specifically for that wrapper. If I'm reading this correctly, the expectation is for something similar to https://docs.rs/openat-ext/0.1.11/openat_ext/trait.OpenatDirExt.html#method.write_file_with.

**Comment by npmccallum** [comment]
> Thanks for the PR! No problem in taking an API break for this.
> 
> However I don't think this a nice way to go, as it discard a lot of useful context around low-level failures, which will in turn make debugging at runtime more painful. I'm not talking hypothetical, I already went through the pains of missing contexts in some obscure corner-cases here.

Why not use `strace` for that rather than crowding Rust return types? That will tell you exactly what syscalls failed and with what values.

> Taking a step back, are your maybe feeling that `thiserror` is bringing in too much dependency/building weight? If so, perhaps we can drop the derive approach and implement the same logic manually?

This is definitely one of my concerns. But I think my preference for having `std::io::Result` is stronger.

> Or is your other patch having impedance mismatches around error types?

This is my biggest concern. The context is: https://github.com/npmccallum/ipvlan where we are doing tons of various syscalls and it is pretty much all `std::io::Result` all the way down.

> In that case I think it may be enough to bridge the error type from<->into io::Error, specifically for that wrapper. If I'm reading this correctly, the expectation is for something similar to https://docs.rs/openat-ext/0.1.11/openat_ext/trait.OpenatDirExt.html#method.write_file_with.

That will still force an unnecessary allocation for `String` as well as pull in the `errno` crate. `std::io::Result` can store the strong or the `errno` without an allocation (unless you're formatting).

**Comment by lucab** [comment]
I slept a bit on this and also tried to cross-check this with a similar discussion occurring at https://github.com/lucab/memfd-rs/pull/20.

Overall a plain `std::io::Error` is not enough, and it is an unfortunate step back in usability.
In order to understand what a random `EPERM` means, the syscall/context around that is required to interpret the specific semantics. `strace`ing is not a solution here: it doesn't help the consuming application while it is handling the error, and it needs to be manually performed post-facto with local access.

That said, if some consumers are interested into this, we can definitely adapt the error type into an enum that:
 1. avoids the derive macros and manually implements `std::error::Error`
 2. keeps the `errno::Errno` intact and wrapped into relevant context, so that consumers can match on specific cases

However point 2 is quite burdening and so far I haven't seen any consumer really needing that. Additionally, it would still need a non-errno variant for all the errors not originating from syscalls.

**Pull request closed without merging**
