### PR TITLE
[Features] Capabilities Autogeneration with documentation autogeneration and some optimisations

### PR DESCRIPTION
**Pull request by LeChatP**
This Pull request regroups many features :
1. Capabilities set is defined as a struct instead of HashSet, which manipulate a single unsigned number instead of many insignificant pointers. This struct allows us to define more functions like display or from str.
2. Capabilities Entries are automatically generated from kernel source code because I am too lazy to follow them updated.
3. I parsed the capabilities manual documentation (from manpage-doc), mainly because people need to know their purpose. This autogenerated a function that returns a description of capability passed in the first parameter.

PS. It needs some unit tests, don't worry, I will write them.

### CODE REVIEW

**Comment by lucab** [comment]
Thanks for the PR!
I don't plan to land the logic for auto-generating the list capabilities. New capabilities on the kernel side set are introduced quite rarely (less than once a year), so the additional machinery here is a bit too much.

On the documentation side, we can clearly improve the situation but at the same we will never be able to cover all of the kernel quirks.
We should link more prominently to https://man7.org/linux/man-pages/man7/capabilities.7.html instead of trying to duplicate most of it here.

**Comment by lucab** [comment]
Thinking about this, it would be great if the entries at https://man7.org/linux/man-pages/man7/capabilities.7.html were individually linkable, as that would be my preferred solution. Unfortunately at this they don't seem to have dedicated stable ID in the HTML.

**Comment by LeChatP** [comment]
The online HTML documentation is automatically generated from the TROFF syntax located on the manpages kernel repository [here](https://git.kernel.org/pub/scm/docs/man-pages/man-pages.git/plain/man7/capabilities.7), and because of this older syntax, it is not possible to link to it. So the build.rs render this raw documentation to ASCII with `man` (instead of HTML), and with some regex, the build.rs extract this information. The link used is on the latest version of manpages, so we need to execute build.rs to regenerate the documentation and the latest capabilities set.

Also, I would autogenerate capability because it was easy to do, and so implementing new traits for capability is faster. But if you don't want this feature, I could remove it; It doesn't matter.

Initially I just wanted to optimize this library to remove the HashSet for a single u64 that is much more efficient than calculating hash and manipulating heap pointers for each capability, then I needed to add the From<u8> for Capability, but I was very lazy to write it. So I thought, what If ... And you found everything I've done.

**Comment by lucab** [comment]
> Initially I just wanted to optimize this library to remove the HashSet for a single u64 that is much more efficient than calculating hash and manipulating heap pointers for each capability, then I needed to add the From<u8> for Capability, but I was very lazy to write it.

Thanks for the additional context.
This is a topic which came up already in some past discussions. As I couldn't find those anymore around here, I wrote down the details at https://github.com/lucab/caps-rs/issues/86.
The short summary is that this may make sense to do at some point in the future, but right now the extensive rework and API break is not really worth it from my point of view.

I'm closing the PR now, but thanks again for starting this.
Apologies for not having the HashSet-vs-bitflags discussion clearly written down in a ticket already.

**Pull request closed without merging**
