### PR TITLE
caps: add all() and string conversion

### PR DESCRIPTION
**Pull request by lucab**

### CODE REVIEW

**Comment by lucab** [comment]
@infinity0 mind having a look at this and see if it fits better in your usecase?

**Comment by lucab** [comment]
@vishvananda this also touches into the discussion at https://github.com/oracle/railcar/issues/1, you may want to have a look at it.

**Comment by infinity0** [comment]
Sorry for the delay. Works well for me, though I worry about the long-term maintenance burden for you to keep having to update the caps list plus all this boilerplate.

(See also the minor comment I added to the commit, about matching on `s.uppercase()` instead.)

If you have any advice on easier ways to [fight cargo](https://github.com/infinity0/ambient-rs/commit/7363a5984f901db91e9913df53ddefe53f444e76#diff-80398c5faae3c069e4e6aa2ed11b28c0L7) that would be appreciated.

**Comment by lucab** [comment]
At the rate of new caps being introduced and given the overall small codebase, I think it is fine to live with the boilerplate.

Regarding cargo, you can try pinning directly this git repository and commit. Anyway, I plan to just land #14 and then tag a 0.1.

**Pull request merged**
